// Удалить из исходного файла функции, указанные в аргументах

package main

import (
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"

	"github.com/fpawel/signature-service/internal"
	"golang.org/x/tools/go/ast/astutil"
)

func main() {
	workDir, err := os.Getwd()
	internal.ExitErr(err)

	fileName := filepath.Join(workDir, os.Args[1])

	funcNames := map[string]bool{}
	for _, s := range os.Args[2:] {
		funcNames[s] = true
	}

	fSet := token.NewFileSet()
	file, err := parser.ParseFile(fSet, fileName, nil, parser.ParseComments)
	internal.ExitErr(err)

	file.Comments[0].List[0].Text = "// Code generated by go-swagger; DO NOT EDIT."

	astutil.Apply(file, nil, func(c *astutil.Cursor) bool {
		switch x := c.Node().(type) {
		case *ast.FuncDecl:
			if funcNames[x.Name.Name] {
				c.Delete()
			}
		}
		return true
	})
	fd, err := os.Create(fileName)
	internal.ExitErr(err)
	defer func() {
		_ = fd.Close()
	}()
	internal.ExitErr(printer.Fprint(fd, fSet, file))
}
